apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: mlops/flask-app
          image: 006207983785.dkr.ecr.us-east-2.amazonaws.com/mlops/flask-app:latest
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
          - name: CAPSTONE_TEST
            valueFrom:
              secretKeyRef:
                name: capstone-secret
                key: CAPSTONE_TEST
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: capstone-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: capstone-secret
                key: AWS_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000